name: Run tests

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '.gitattributes'
      - '*.md'
      - '*.rst'
      - 'LICENSE'
      - 'protobuf_list.txt'
      - 'docs/**'
      - 'protobufs/**'
      - 'recipes/**'
  workflow_call:
  workflow_dispatch:

concurrency:
  group: run-tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7

      - name: Set up Poetry
        uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{ matrix.python-version }}
          install-args: --extras client --with dev

      - name: Run tests
        run: poetry run pytest -p no:cov
